### ISSUE TITLE
META: gg.top should depend on gg

### ISSUE THREAD

**Issue by whitequark** [dbuenzli/gg#1]
Subject says it. I don't think there is a reason to require gg.top but not gg, and adding a dependency means one #require less.

**Comment by dbuenzli** [comment]
You've got things the wrong way around, see this [line](https://github.com/dbuenzli/gg/blob/master/pkg/META#L9). Just `#require "gg"` (sorry for the unbound values in the released version):

```
# #require "gg";;
/Users/dbuenzli/.opam/4.01.0/lib/ocaml/unix.cma: loaded
/Users/dbuenzli/.opam/4.01.0/lib/ocaml/bigarray.cma: loaded
/Users/dbuenzli/.opam/4.01.0/lib/gg: added to search path
/Users/dbuenzli/.opam/4.01.0/lib/gg/gg.cma: loaded
/Users/dbuenzli/.opam/4.01.0/lib/gg/gg_top.cma: loaded
Unbound value Raster.pp_buffer.
Unbound value Raster.pp_sample_format.
```

**Comment by whitequark** [comment]
Oops. Sorry for the noise.

**Comment by dbuenzli** [comment]
@whitequark Actually I think that what you assumed maybe the right thing to do. The problem with my current toplevel scheme, is that I don't give the choice to people. If they `#require "gg"`, the damn thing will `open Gg` and that may be annoying for some reason (e.g. name clashes). 

So I think it would be better if `#require "gg"` wouldn't do anything and `require "gg.top"` would depend on `gg` and do the `open Gg` and install the printers. So that you are actually given the choice. 

What do you think ?

**Comment by whitequark** [comment]
@dbuenzli I think the scheme you propose is much more clear for the users. I certainly like it more; a package shouldn't behave differently when loaded in toplevel and when not.

**Comment by dbuenzli** [comment]
@whitequark Yes. I'm going to gradually change that in my distributed packages.
